id: IDB15ED00
legacy_id: P005368
ocr_import_info:
  bdrc_scan_id: W1KG4473
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T15:29:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T16:42:12.478961+00:00'
last_modified: 2022-09-01 00:42:39.878021
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4473
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4473
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་གདམས་གླེགས་བམ།
statistics:
  ocr_word_mean_confidence_index: 0.7218042760317266
  ocr_word_median_confidence_index: 0.8100000023841858
quality: null
bases:
  I1KG4501:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4501
      total_pages: 444
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4501.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7738532401376621
    legacy_id: v001
  I1KG4502:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4502
      total_pages: 436
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG4502.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6662047256931983
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
