id: IDB15ED00
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T15:32:44+00:00'
last_modified: '2022-06-08T02:35:28.075365+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4473
  title: བཀའ་གདམས་གླེགས་བམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    67BD:
      image_group_id: I1KG4501
      title: ''
      total_pages: 444
      order: 1
      base_file: 67BD.txt
    4A56:
      image_group_id: I1KG4502
      title: ''
      total_pages: 436
      order: 2
      base_file: 4A56.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
